#!/bin/bash

# Defaults:
RATIO_OF_CAPACITY_TO_USE=0.8
COMMA_SEPARATED_FILE_EXTENSIONS=jpeg,jpg
directory=.
encryption_algorithm=rijndael-256
input_filename=-
mode="embed"

find_files() {
  directory="$1"
  if [ -z "${directory}" ]; then
    directory=.
  fi
  find_command="find \"${directory}\" -type f $( get_find_options_from_comma_separated_file_extensions "${COMMA_SEPARATED_FILE_EXTENSIONS}" )"
  eval ${find_command} | sort
}

get_find_options_from_comma_separated_file_extensions() {
  IFS=, read -a extensions <<<$1
  i=0
  FIND_OPTIONS="\\("
  while [ $i -lt ${#extensions[*]} ]; do
    if [ $i -gt 0 ]; then
      FIND_OPTIONS="${FIND_OPTIONS} -o"
    fi
    FIND_OPTIONS="${FIND_OPTIONS} -iname '*.${extensions[$i]}'"
    i=$(( i + 1 ))
  done
  FIND_OPTIONS="${FIND_OPTIONS} \\)"
  echo "${FIND_OPTIONS}"
}

get_file_capacity_in_bytes() {
  kB=$( steghide info -p '' "${1}" 2>/dev/null | grep capacity | sed -e 's/.*capacity: *\([0-9.]*\) \(KB\|Byte\).*$/\1 \2/' | sed -e 's/KB/* 1024/' -e 's/Byte/* 1/' )
  # divide capacity reported by two; it often doesn't seem to fit
  echo "scale=3
${kB} * ${RATIO_OF_CAPACITY_TO_USE}" | bc | sed -e 's/\..*$//'
}

# returns 0 if the number of bytes specified in $1 can be fit into the
# capacity of the files provided in the lines of $2; 1 otherwise.
check_total_capacity_in_bytes() {
  required_capacity_in_bytes=$1
  total_capacity_in_bytes=0
  total_capacity_in_bytes=$( echo "$2" | while read file; do
    echo "Estimating total capacity; currently at ${file} with total capacity so far ${total_capacity_in_bytes}B" >&2
    total_capacity_in_bytes=$(( ${total_capacity_in_bytes} + $( get_file_capacity_in_bytes "${file}" ) ))
    echo "${total_capacity_in_bytes}"
    if [ ${total_capacity_in_bytes} -ge ${required_capacity_in_bytes} ]; then
      exit 0
    fi
  done | tail -1 )
  if [ ${total_capacity_in_bytes} -ge ${required_capacity_in_bytes} ]; then
    echo "Sufficient capacity (${total_capacity_in_bytes}B sufficient to hold ${required_capacity_in_bytes}B)" >&2
    return 0
  else
    echo "Inufficient capacity (${total_capacity_in_bytes}B not sufficient to hold ${required_capacity_in_bytes}B)" >&2
    return 1
  fi
}

get_file_size_in_bytes() {
  wc -c "${1}" | while read size filename; do echo "${size}"; done
}

clean_up() {
  echo "Cleaning up..." >&2
  if [ -n $tmpfile ]; then
    rm "${tmpfile}" 2>/dev/null
  fi
}

show_usage() {
  echo "Usage: $0 [ -x ] [ -d <directory-with-cover-files> ] [ -p <passphrase> ] [ -e <encryption-algorithm> ] [ -f <comma-separated-list-of-file-extensions> ] [ -h ] [ <embed-file> ]"
  echo
  echo "If -x is provided, extracts a file from the cover files; otherwise, the <embed-file> or standard input"
  echo "will be embedded into the cover files in place, modifying one or more of the cover files."
  echo "To see the list of available encryption algorithms call \"steghide encinfo\"."
  echo "If a directory is provided using -d, all JPEG/jpeg/JPG/jpg files are listed and sorted by path and"
  echo "the files will be used in that order as cover files to extract or embed the content of the embed file. If no"
  echo "directory is provided with -d, the cover files will be searched recursively, starting from the current directory."
  echo "If no <embed-file> is provided, the standard input will be embedded, or extraction will go to standard output, respectively."
  echo "If no passphrase is provided using the -p parameter, the tool will prompt for one."
  echo "To override the default file extension list \"jpeg,jpg\", use the -f parameter. File name matching"
  echo "is case-insensitive, so \"-f wav\" will match all .wav and .WAV (and even .WaV) files."
  echo "Progress output goes to standard error."
  echo "The program exits with code 0 in case all went well; 1 in case there was input left that did not"
  echo "fit into the cover file(s), and 2 if this usage hint was requested."
  echo "Request this usage hint by invoking with -h or without any arguments."
}

# Check for help scenario:
if [ $# = 0 ]; then
  show_usage
  exit 2
fi
# Parsing options:
options=':d:p:e:f:xh'
while getopts $options option
do
    case $option in
        d) directory="${OPTARG}";;
        p) passphrase="${OPTARG}";;
        e) encryption_algorithm="${OPTARG}";;
	f) COMMA_SEPARATED_FILE_EXTENSIONS="${OPTARG}";;
        x) mode="extract";;
        h) show_usage; exit 2;;
        \?) echo "Invalid option"
            exit 4;;
    esac
done
shift $((OPTIND-1))
# Ask for passphrase if not provided
if [ -z ${passphrase} ]; then
  read -s -p "Passphrase (not echoed): " passphrase
  echo
  if [ "${mode}" = "embed" ]; then
    read -s -p "Passphrase confirmation (not echoed): " passphrase2
    echo
    if [ "${passphrase}" != "${passphrase2}" ]; then
      echo "Passwords don't match" >&2
      exit 5
    fi
  fi
fi
# Loop over the output files, determine capacity, then read that many
# bytes from the input and encode them in the output file.
# If data is remaining after all files have been processed, flag this
# as an error.
echo "Finding files..." >&2
files=$( find_files "${directory}" )
if [ "${mode}" = "embed" ]; then
  echo "Embedding" >&2
  # Determine input file to handle; no input file parameter means stdin and we copy that to a tmp file
  if [ $# -gt 0 ]; then
    input_filename="${1}"
  else
    tmpfile=$( mktemp )
    input_filename="${tmpfile}"
    cat >"${tmpfile}"
  fi
  total_size_in_bytes=$( get_file_size_in_bytes "${input_filename}" )
  echo "File size to embed is ${total_size_in_bytes} bytes" >&2
  if ! check_total_capacity_in_bytes ${total_size_in_bytes} "${files}"; then
    exit 1
  fi
  export size_encoded_so_far_in_bytes=0
  exec 4<"${input_filename}"
  size_encoded_so_far_in_bytes=$(
    echo "${files}" | while read file; do
      file_capacity_in_bytes=$( get_file_capacity_in_bytes "${file}" )
      echo "File: ${file} has capacity ${file_capacity_in_bytes}" >&2
      head -c ${file_capacity_in_bytes} <&4 | steghide embed -p "${passphrase}" -cf "${file}" -e ${encryption_algorithm} >&2
      size_encoded_so_far_in_bytes=$(( ${size_encoded_so_far_in_bytes} + ${file_capacity_in_bytes} ))
      echo "size_encoded_so_far_in_bytes is ${size_encoded_so_far_in_bytes}" >&2
      echo "${size_encoded_so_far_in_bytes}"
      if [ ${size_encoded_so_far_in_bytes} -ge ${total_size_in_bytes} ]; then
        echo "Last output file used: ${file}" >&2
        exit 0
      fi
    done | tail -1
  )
  echo "Encoded bytes: ${size_encoded_so_far_in_bytes}" >&2
  # Clean up:
  clean_up
  # Error check:
  if [ ${size_encoded_so_far_in_bytes} -lt ${total_size_in_bytes} ]; then
    echo "Not all ${total_size_in_bytes} bytes were embedded but only ${size_encoded_so_far_in_bytes}." >&2
    exit 1
  fi
elif [ "${mode}" = "extract" ]; then
  if [ $# -gt 0 ]; then
    output_filename="${1}"
    exec 1>"${output_filename}"
    echo "Extracting embedded content to file ${output_filename}" >&2
  else
    echo "Extracting embedded content to standard output" >&2
  fi
  echo "${files}" | while read file; do
    echo "Looking for embedded content in ${file}..." >&2
    if ! steghide extract -p "${passphrase}" -sf "${file}" -xf - 2>/dev/null; then
      echo "No more content found embedded in ${file}. Finished." >&2
      exit 0
    fi
  done
else
  echo "Unknown mode ${mode}" >&2
  exit 3
fi
